theme: jekyll-theme-cayman
title: " "
description: "Continual Open Set Domain Adaptation Towards Object Recognition For Home Robot"
logo: "cosda/logo/logo.png"
show_downloads: true
github:
  tar_url: "https://drive.google.com/file/d/1Fc0MJtJT5lNNpt7S65BCeLSjg7Z1jrQ1/view?usp=sharing"
